// Date: 1/3/2015 11:20:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package zero9010.miscobjects.client.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Tent extends ModelBase
{
  //fields
    ModelRenderer Right1;
    ModelRenderer Right2;
    ModelRenderer Right3;
    ModelRenderer Right4;
    ModelRenderer Right5;
    ModelRenderer right6;
    ModelRenderer Right7;
    ModelRenderer Right8;
    ModelRenderer Floor;
    ModelRenderer Left1;
    ModelRenderer Left2;
    ModelRenderer Left3;
    ModelRenderer Left4;
    ModelRenderer Left5;
    ModelRenderer Left6;
    ModelRenderer Left7;
    ModelRenderer Left9;
    ModelRenderer Post1;
    ModelRenderer Post2;
  
  public Tent()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Right1 = new ModelRenderer(this, 0, 0);
      Right1.addBox(0F, 0F, 0F, 1, 2, 32);
      Right1.setRotationPoint(-8F, 22F, -8F);
      Right1.setTextureSize(128, 64);
      Right1.mirror = true;
      setRotation(Right1, 0F, 0F, 0F);
      Right2 = new ModelRenderer(this, 0, 0);
      Right2.addBox(0F, 0F, 0F, 1, 2, 32);
      Right2.setRotationPoint(-7F, 20F, -8F);
      Right2.setTextureSize(128, 64);
      Right2.mirror = true;
      setRotation(Right2, 0F, 0F, 0F);
      Right3 = new ModelRenderer(this, 0, 0);
      Right3.addBox(0F, 0F, 0F, 1, 2, 32);
      Right3.setRotationPoint(-6F, 18F, -8F);
      Right3.setTextureSize(128, 64);
      Right3.mirror = true;
      setRotation(Right3, 0F, 0F, 0F);
      Right4 = new ModelRenderer(this, 0, 0);
      Right4.addBox(0F, 0F, 0F, 1, 2, 32);
      Right4.setRotationPoint(-5F, 16F, -8F);
      Right4.setTextureSize(128, 64);
      Right4.mirror = true;
      setRotation(Right4, 0F, 0F, 0F);
      Right5 = new ModelRenderer(this, 0, 0);
      Right5.addBox(0F, 0F, 0F, 1, 2, 32);
      Right5.setRotationPoint(-4F, 14F, -8F);
      Right5.setTextureSize(128, 64);
      Right5.mirror = true;
      setRotation(Right5, 0F, 0F, 0F);
      right6 = new ModelRenderer(this, 0, 0);
      right6.addBox(0F, 0F, 0F, 1, 2, 32);
      right6.setRotationPoint(-3F, 12F, -8F);
      right6.setTextureSize(128, 64);
      right6.mirror = true;
      setRotation(right6, 0F, 0F, 0F);
      Right7 = new ModelRenderer(this, 0, 0);
      Right7.addBox(0F, 0F, 0F, 1, 2, 32);
      Right7.setRotationPoint(-2F, 10F, -8F);
      Right7.setTextureSize(128, 64);
      Right7.mirror = true;
      setRotation(Right7, 0F, 0F, 0F);
      Right8 = new ModelRenderer(this, 0, 0);
      Right8.addBox(0F, 0F, 0F, 1, 2, 32);
      Right8.setRotationPoint(-1F, 8F, -8F);
      Right8.setTextureSize(128, 64);
      Right8.mirror = true;
      setRotation(Right8, 0F, 0F, 0F);
      Floor = new ModelRenderer(this, 2, 0);
      Floor.addBox(0F, 0F, 0F, 16, 0, 32);
      Floor.setRotationPoint(-8F, 23.99F, -8F);
      Floor.setTextureSize(128, 64);
      Floor.mirror = true;
      setRotation(Floor, 0F, 0F, 0F);
      Left1 = new ModelRenderer(this, 0, 0);
      Left1.addBox(0F, 0F, 0F, 1, 2, 32);
      Left1.setRotationPoint(7F, 22F, -8F);
      Left1.setTextureSize(128, 64);
      Left1.mirror = true;
      setRotation(Left1, 0F, 0F, 0F);
      Left2 = new ModelRenderer(this, 0, 0);
      Left2.addBox(0F, 0F, 0F, 1, 2, 32);
      Left2.setRotationPoint(6F, 20F, -8F);
      Left2.setTextureSize(128, 64);
      Left2.mirror = true;
      setRotation(Left2, 0F, 0F, 0F);
      Left3 = new ModelRenderer(this, 0, 0);
      Left3.addBox(0F, 0F, 0F, 1, 2, 32);
      Left3.setRotationPoint(5F, 18F, -8F);
      Left3.setTextureSize(128, 64);
      Left3.mirror = true;
      setRotation(Left3, 0F, 0F, 0F);
      Left4 = new ModelRenderer(this, 0, 0);
      Left4.addBox(0F, 0F, 0F, 1, 2, 32);
      Left4.setRotationPoint(4F, 16F, -8F);
      Left4.setTextureSize(128, 64);
      Left4.mirror = true;
      setRotation(Left4, 0F, 0F, 0F);
      Left5 = new ModelRenderer(this, 0, 0);
      Left5.addBox(0F, 0F, 0F, 1, 2, 32);
      Left5.setRotationPoint(3F, 14F, -8F);
      Left5.setTextureSize(128, 64);
      Left5.mirror = true;
      setRotation(Left5, 0F, 0F, 0F);
      Left6 = new ModelRenderer(this, 0, 0);
      Left6.addBox(0F, 0F, 0F, 1, 2, 32);
      Left6.setRotationPoint(2F, 12F, -8F);
      Left6.setTextureSize(128, 64);
      Left6.mirror = true;
      setRotation(Left6, 0F, 0F, 0F);
      Left7 = new ModelRenderer(this, 0, 0);
      Left7.addBox(0F, 0F, 0F, 1, 2, 32);
      Left7.setRotationPoint(1F, 10F, -8F);
      Left7.setTextureSize(128, 64);
      Left7.mirror = true;
      setRotation(Left7, 0F, 0F, 0F);
      Left9 = new ModelRenderer(this, 0, 0);
      Left9.addBox(0F, 0F, 0F, 1, 2, 32);
      Left9.setRotationPoint(0F, 8F, -8F);
      Left9.setTextureSize(128, 64);
      Left9.mirror = true;
      setRotation(Left9, 0F, 0F, 0F);
      Post1 = new ModelRenderer(this, 0, 0);
      Post1.addBox(0F, 0F, 0F, 2, 14, 1);
      Post1.setRotationPoint(-1F, 10F, -8F);
      Post1.setTextureSize(128, 64);
      Post1.mirror = true;
      setRotation(Post1, 0F, 0F, 0F);
      Post2 = new ModelRenderer(this, 0, 0);
      Post2.addBox(0F, 0F, 0F, 2, 14, 1);
      Post2.setRotationPoint(-1F, 10F, 23F);
      Post2.setTextureSize(128, 64);
      Post2.mirror = true;
      setRotation(Post2, 0F, 0F, 0F);
  }
  
  public void render(float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Right1.render(f5);
    Right2.render(f5);
    Right3.render(f5);
    Right4.render(f5);
    Right5.render(f5);
    right6.render(f5);
    Right7.render(f5);
    Right8.render(f5);
    Floor.render(f5);
    Left1.render(f5);
    Left2.render(f5);
    Left3.render(f5);
    Left4.render(f5);
    Left5.render(f5);
    Left6.render(f5);
    Left7.render(f5);
    Left9.render(f5);
    Post1.render(f5);
    Post2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
